version: "3.7"
services:
  db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cccat16
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
